# Generated by Django 5.0.6 on 2024-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoinment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='name',
            new_name='patient',
        ),
    ]
